-- V3: create categories and subcategories for inquiry taxonomy

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(120) NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    display_order INT NOT NULL,
    UNIQUE KEY uq_categories_slug (slug),
    KEY idx_categories_active_order (active, display_order)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS subcategories (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(120) NOT NULL,
    active TINYINT(1) NOT NULL DEFAULT 1,
    display_order INT NOT NULL,
    UNIQUE KEY uq_subcategories_category_slug (category_id, slug),
    KEY idx_subcategories_category (category_id),
    KEY idx_subcategories_active_order (active, display_order),
    CONSTRAINT fk_subcategories_category_id
        FOREIGN KEY (category_id) REFERENCES categories(id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
) ENGINE=InnoDB;

-- Seed categories
INSERT INTO categories (name, slug, active, display_order) VALUES
    ('Home', 'home', 1, 1),
    ('Office / Corporate', 'office-corporate', 1, 2),
    ('Hospital / Healthcare', 'hospital-healthcare', 1, 3),
    ('Hotel / Hospitality', 'hotel-hospitality', 1, 4),
    ('Institute / Education', 'institute-education', 1, 5),
    ('Custom', 'custom', 1, 6),
    ('Retail / Showroom', 'retail-showroom', 1, 7),
    ('Industrial / Warehouse', 'industrial-warehouse', 1, 8),
    ('Outdoor / Landscape', 'outdoor-landscape', 1, 9),
    ('Religious / Community', 'religious-community', 1, 10)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    active = VALUES(active),
    display_order = VALUES(display_order);

-- Seed subcategories
INSERT INTO subcategories (category_id, name, slug, active, display_order) VALUES
    ((SELECT id FROM categories WHERE slug = 'home'), 'Bedroom', 'bedroom', 1, 1),
    ((SELECT id FROM categories WHERE slug = 'home'), 'Living Room', 'living-room', 1, 2),
    ((SELECT id FROM categories WHERE slug = 'home'), 'Kitchen', 'kitchen', 1, 3),
    ((SELECT id FROM categories WHERE slug = 'home'), 'Dining Room', 'dining-room', 1, 4),
    ((SELECT id FROM categories WHERE slug = 'home'), 'Bathroom Vanity', 'bathroom-vanity', 1, 5),
    ((SELECT id FROM categories WHERE slug = 'home'), 'Wardrobe', 'wardrobe', 1, 6),
    ((SELECT id FROM categories WHERE slug = 'home'), 'Modular Storage', 'modular-storage', 1, 7),
    ((SELECT id FROM categories WHERE slug = 'home'), 'TV Unit', 'tv-unit', 1, 8),
    ((SELECT id FROM categories WHERE slug = 'home'), 'Balcony', 'balcony', 1, 9),
    ((SELECT id FROM categories WHERE slug = 'home'), 'Full Home Interior', 'full-home-interior', 1, 10),
    ((SELECT id FROM categories WHERE slug = 'home'), 'Home Office', 'home-office', 1, 11),
    ((SELECT id FROM categories WHERE slug = 'home'), 'Kids Room', 'kids-room', 1, 12),
    ((SELECT id FROM categories WHERE slug = 'home'), 'Entryway / Foyer', 'entryway-foyer', 1, 13),
    ((SELECT id FROM categories WHERE slug = 'home'), 'Utility / Laundry', 'utility-laundry', 1, 14),
    ((SELECT id FROM categories WHERE slug = 'home'), 'Pooja Room', 'pooja-room', 1, 15),

    ((SELECT id FROM categories WHERE slug = 'office-corporate'), 'Executive Desk', 'executive-desk', 1, 1),
    ((SELECT id FROM categories WHERE slug = 'office-corporate'), 'Workstation', 'workstation', 1, 2),
    ((SELECT id FROM categories WHERE slug = 'office-corporate'), 'Conference Table', 'conference-table', 1, 3),
    ((SELECT id FROM categories WHERE slug = 'office-corporate'), 'Reception Desk', 'reception-desk', 1, 4),
    ((SELECT id FROM categories WHERE slug = 'office-corporate'), 'Cabin Interior', 'cabin-interior', 1, 5),
    ((SELECT id FROM categories WHERE slug = 'office-corporate'), 'Storage Cabinet', 'storage-cabinet', 1, 6),
    ((SELECT id FROM categories WHERE slug = 'office-corporate'), 'Filing System', 'filing-system', 1, 7),
    ((SELECT id FROM categories WHERE slug = 'office-corporate'), 'Pantry Area', 'pantry-area', 1, 8),
    ((SELECT id FROM categories WHERE slug = 'office-corporate'), 'Meeting Room', 'meeting-room', 1, 9),
    ((SELECT id FROM categories WHERE slug = 'office-corporate'), 'Full Office Setup', 'full-office-setup', 1, 10),
    ((SELECT id FROM categories WHERE slug = 'office-corporate'), 'Open Office Layout', 'open-office-layout', 1, 11),
    ((SELECT id FROM categories WHERE slug = 'office-corporate'), 'Training Room', 'training-room', 1, 12),
    ((SELECT id FROM categories WHERE slug = 'office-corporate'), 'Phone Booth / Focus Pod', 'phone-booth-focus-pod', 1, 13),
    ((SELECT id FROM categories WHERE slug = 'office-corporate'), 'Breakout Area', 'breakout-area', 1, 14),
    ((SELECT id FROM categories WHERE slug = 'office-corporate'), 'Server Room', 'server-room', 1, 15),

    ((SELECT id FROM categories WHERE slug = 'hospital-healthcare'), 'Reception Counter', 'reception-counter', 1, 1),
    ((SELECT id FROM categories WHERE slug = 'hospital-healthcare'), 'Patient Bed Unit', 'patient-bed-unit', 1, 2),
    ((SELECT id FROM categories WHERE slug = 'hospital-healthcare'), 'Waiting Bench', 'waiting-bench', 1, 3),
    ((SELECT id FROM categories WHERE slug = 'hospital-healthcare'), 'Nursing Station', 'nursing-station', 1, 4),
    ((SELECT id FROM categories WHERE slug = 'hospital-healthcare'), 'Lab Furniture', 'lab-furniture', 1, 5),
    ((SELECT id FROM categories WHERE slug = 'hospital-healthcare'), 'Pharmacy Counter', 'pharmacy-counter', 1, 6),
    ((SELECT id FROM categories WHERE slug = 'hospital-healthcare'), 'Doctor Cabin', 'doctor-cabin', 1, 7),
    ((SELECT id FROM categories WHERE slug = 'hospital-healthcare'), 'ICU Storage', 'icu-storage', 1, 8),
    ((SELECT id FROM categories WHERE slug = 'hospital-healthcare'), 'Medical Ward Setup', 'medical-ward-setup', 1, 9),
    ((SELECT id FROM categories WHERE slug = 'hospital-healthcare'), 'Full Hospital Interior', 'full-hospital-interior', 1, 10),
    ((SELECT id FROM categories WHERE slug = 'hospital-healthcare'), 'Triage Area', 'triage-area', 1, 11),
    ((SELECT id FROM categories WHERE slug = 'hospital-healthcare'), 'Consultation Room', 'consultation-room', 1, 12),
    ((SELECT id FROM categories WHERE slug = 'hospital-healthcare'), 'OT Storage', 'ot-storage', 1, 13),
    ((SELECT id FROM categories WHERE slug = 'hospital-healthcare'), 'Sample Collection', 'sample-collection', 1, 14),
    ((SELECT id FROM categories WHERE slug = 'hospital-healthcare'), 'Imaging Room', 'imaging-room', 1, 15),

    ((SELECT id FROM categories WHERE slug = 'hotel-hospitality'), 'Reception Desk', 'reception-desk', 1, 1),
    ((SELECT id FROM categories WHERE slug = 'hotel-hospitality'), 'Guest Room Furniture', 'guest-room-furniture', 1, 2),
    ((SELECT id FROM categories WHERE slug = 'hotel-hospitality'), 'Lobby Seating', 'lobby-seating', 1, 3),
    ((SELECT id FROM categories WHERE slug = 'hotel-hospitality'), 'Restaurant Furniture', 'restaurant-furniture', 1, 4),
    ((SELECT id FROM categories WHERE slug = 'hotel-hospitality'), 'Banquet Hall Setup', 'banquet-hall-setup', 1, 5),
    ((SELECT id FROM categories WHERE slug = 'hotel-hospitality'), 'Bar Counter', 'bar-counter', 1, 6),
    ((SELECT id FROM categories WHERE slug = 'hotel-hospitality'), 'Modular Wardrobe', 'modular-wardrobe', 1, 7),
    ((SELECT id FROM categories WHERE slug = 'hotel-hospitality'), 'Kitchen Utility', 'kitchen-utility', 1, 8),
    ((SELECT id FROM categories WHERE slug = 'hotel-hospitality'), 'Outdoor Lounge', 'outdoor-lounge', 1, 9),
    ((SELECT id FROM categories WHERE slug = 'hotel-hospitality'), 'Full Property Setup', 'full-property-setup', 1, 10),
    ((SELECT id FROM categories WHERE slug = 'hotel-hospitality'), 'Spa Setup', 'spa-setup', 1, 11),
    ((SELECT id FROM categories WHERE slug = 'hotel-hospitality'), 'Gym Fitout', 'gym-fitout', 1, 12),
    ((SELECT id FROM categories WHERE slug = 'hotel-hospitality'), 'Staff Quarters', 'staff-quarters', 1, 13),
    ((SELECT id FROM categories WHERE slug = 'hotel-hospitality'), 'Back Office', 'back-office', 1, 14),
    ((SELECT id FROM categories WHERE slug = 'hotel-hospitality'), 'Laundry Room', 'laundry-room', 1, 15),

    ((SELECT id FROM categories WHERE slug = 'institute-education'), 'Classroom Bench', 'classroom-bench', 1, 1),
    ((SELECT id FROM categories WHERE slug = 'institute-education'), 'Teacher Desk', 'teacher-desk', 1, 2),
    ((SELECT id FROM categories WHERE slug = 'institute-education'), 'Announcement Board', 'announcement-board', 1, 3),
    ((SELECT id FROM categories WHERE slug = 'institute-education'), 'Laboratory Furniture', 'laboratory-furniture', 1, 4),
    ((SELECT id FROM categories WHERE slug = 'institute-education'), 'Library Shelving', 'library-shelving', 1, 5),
    ((SELECT id FROM categories WHERE slug = 'institute-education'), 'Reception Counter', 'reception-counter', 1, 6),
    ((SELECT id FROM categories WHERE slug = 'institute-education'), 'Hostel Furniture', 'hostel-furniture', 1, 7),
    ((SELECT id FROM categories WHERE slug = 'institute-education'), 'Auditorium Seating', 'auditorium-seating', 1, 8),
    ((SELECT id FROM categories WHERE slug = 'institute-education'), 'Admin Office', 'admin-office', 1, 9),
    ((SELECT id FROM categories WHERE slug = 'institute-education'), 'Full Campus Setup', 'full-campus-setup', 1, 10),
    ((SELECT id FROM categories WHERE slug = 'institute-education'), 'Cafeteria Seating', 'cafeteria-seating', 1, 11),
    ((SELECT id FROM categories WHERE slug = 'institute-education'), 'Computer Lab', 'computer-lab', 1, 12),
    ((SELECT id FROM categories WHERE slug = 'institute-education'), 'Staff Room', 'staff-room', 1, 13),
    ((SELECT id FROM categories WHERE slug = 'institute-education'), 'Principal Office', 'principal-office', 1, 14),
    ((SELECT id FROM categories WHERE slug = 'institute-education'), 'Sports Facility Storage', 'sports-facility-storage', 1, 15),

    ((SELECT id FROM categories WHERE slug = 'custom'), 'Bespoke Wardrobe', 'bespoke-wardrobe', 1, 1),
    ((SELECT id FROM categories WHERE slug = 'custom'), 'CNC Design', 'cnc-design', 1, 2),
    ((SELECT id FROM categories WHERE slug = 'custom'), 'Display Unit', 'display-unit', 1, 3),
    ((SELECT id FROM categories WHERE slug = 'custom'), 'Retail Counter', 'retail-counter', 1, 4),
    ((SELECT id FROM categories WHERE slug = 'custom'), 'Exhibition Booth', 'exhibition-booth', 1, 5),
    ((SELECT id FROM categories WHERE slug = 'custom'), 'Artisan Piece', 'artisan-piece', 1, 6),
    ((SELECT id FROM categories WHERE slug = 'custom'), 'Renovation', 'renovation', 1, 7),
    ((SELECT id FROM categories WHERE slug = 'custom'), 'Full Custom Requirement', 'full-custom-requirement', 1, 8),
    ((SELECT id FROM categories WHERE slug = 'custom'), 'Partition Screens', 'partition-screens', 1, 9),
    ((SELECT id FROM categories WHERE slug = 'custom'), 'Acoustic Panels', 'acoustic-panels', 1, 10),
    ((SELECT id FROM categories WHERE slug = 'custom'), 'Smart Furniture', 'smart-furniture', 1, 11),
    ((SELECT id FROM categories WHERE slug = 'custom'), 'Prototype', 'prototype', 1, 12),
    ((SELECT id FROM categories WHERE slug = 'custom'), 'Staircase / Handrail', 'staircase-handrail', 1, 13),

    ((SELECT id FROM categories WHERE slug = 'retail-showroom'), 'Display Shelving', 'display-shelving', 1, 1),
    ((SELECT id FROM categories WHERE slug = 'retail-showroom'), 'Checkout Counter', 'checkout-counter', 1, 2),
    ((SELECT id FROM categories WHERE slug = 'retail-showroom'), 'Trial Room', 'trial-room', 1, 3),
    ((SELECT id FROM categories WHERE slug = 'retail-showroom'), 'Gondola Rack', 'gondola-rack', 1, 4),
    ((SELECT id FROM categories WHERE slug = 'retail-showroom'), 'Backroom Storage', 'backroom-storage', 1, 5),
    ((SELECT id FROM categories WHERE slug = 'retail-showroom'), 'POS Kiosk', 'pos-kiosk', 1, 6),
    ((SELECT id FROM categories WHERE slug = 'retail-showroom'), 'Visual Merchandising Wall', 'visual-merchandising-wall', 1, 7),
    ((SELECT id FROM categories WHERE slug = 'retail-showroom'), 'Product Island Table', 'product-island-table', 1, 8),
    ((SELECT id FROM categories WHERE slug = 'retail-showroom'), 'Reception Desk', 'reception-desk', 1, 9),
    ((SELECT id FROM categories WHERE slug = 'retail-showroom'), 'Full Store Fitout', 'full-store-fitout', 1, 10),

    ((SELECT id FROM categories WHERE slug = 'industrial-warehouse'), 'Packing Station', 'packing-station', 1, 1),
    ((SELECT id FROM categories WHERE slug = 'industrial-warehouse'), 'Heavy Duty Shelving', 'heavy-duty-shelving', 1, 2),
    ((SELECT id FROM categories WHERE slug = 'industrial-warehouse'), 'Tool Cabinet', 'tool-cabinet', 1, 3),
    ((SELECT id FROM categories WHERE slug = 'industrial-warehouse'), 'Workbench', 'workbench', 1, 4),
    ((SELECT id FROM categories WHERE slug = 'industrial-warehouse'), 'Locker Room', 'locker-room', 1, 5),
    ((SELECT id FROM categories WHERE slug = 'industrial-warehouse'), 'Safety Station', 'safety-station', 1, 6),
    ((SELECT id FROM categories WHERE slug = 'industrial-warehouse'), 'Pallet Racking', 'pallet-racking', 1, 7),
    ((SELECT id FROM categories WHERE slug = 'industrial-warehouse'), 'Spare Parts Storage', 'spare-parts-storage', 1, 8),
    ((SELECT id FROM categories WHERE slug = 'industrial-warehouse'), 'QA Inspection Table', 'qa-inspection-table', 1, 9),
    ((SELECT id FROM categories WHERE slug = 'industrial-warehouse'), 'Supervisor Cabin', 'supervisor-cabin', 1, 10),

    ((SELECT id FROM categories WHERE slug = 'outdoor-landscape'), 'Pergola', 'pergola', 1, 1),
    ((SELECT id FROM categories WHERE slug = 'outdoor-landscape'), 'Garden Seating', 'garden-seating', 1, 2),
    ((SELECT id FROM categories WHERE slug = 'outdoor-landscape'), 'Outdoor Kitchen', 'outdoor-kitchen', 1, 3),
    ((SELECT id FROM categories WHERE slug = 'outdoor-landscape'), 'Decking', 'decking', 1, 4),
    ((SELECT id FROM categories WHERE slug = 'outdoor-landscape'), 'Poolside Cabana', 'poolside-cabana', 1, 5),
    ((SELECT id FROM categories WHERE slug = 'outdoor-landscape'), 'Gazebo', 'gazebo', 1, 6),
    ((SELECT id FROM categories WHERE slug = 'outdoor-landscape'), 'Outdoor Bar Counter', 'outdoor-bar-counter', 1, 7),
    ((SELECT id FROM categories WHERE slug = 'outdoor-landscape'), 'Planter Box', 'planter-box', 1, 8),
    ((SELECT id FROM categories WHERE slug = 'outdoor-landscape'), 'Patio Dining', 'patio-dining', 1, 9),
    ((SELECT id FROM categories WHERE slug = 'outdoor-landscape'), 'Terrace Seating', 'terrace-seating', 1, 10),

    ((SELECT id FROM categories WHERE slug = 'religious-community'), 'Pooja Mandir', 'pooja-mandir', 1, 1),
    ((SELECT id FROM categories WHERE slug = 'religious-community'), 'Community Hall Seating', 'community-hall-seating', 1, 2),
    ((SELECT id FROM categories WHERE slug = 'religious-community'), 'Donation Counter', 'donation-counter', 1, 3),
    ((SELECT id FROM categories WHERE slug = 'religious-community'), 'Storage Cabinets', 'storage-cabinets', 1, 4),
    ((SELECT id FROM categories WHERE slug = 'religious-community'), 'Reception Counter', 'reception-counter', 1, 5),
    ((SELECT id FROM categories WHERE slug = 'religious-community'), 'Audio Visual Console', 'audio-visual-console', 1, 6),
    ((SELECT id FROM categories WHERE slug = 'religious-community'), 'Library Shelving', 'library-shelving', 1, 7),
    ((SELECT id FROM categories WHERE slug = 'religious-community'), 'Shoe Rack Area', 'shoe-rack-area', 1, 8),
    ((SELECT id FROM categories WHERE slug = 'religious-community'), 'Stage Backdrop', 'stage-backdrop', 1, 9),
    ((SELECT id FROM categories WHERE slug = 'religious-community'), 'Lobby Seating', 'lobby-seating', 1, 10)
ON DUPLICATE KEY UPDATE
    name = VALUES(name),
    active = VALUES(active),
    display_order = VALUES(display_order),
    category_id = VALUES(category_id);
